linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    check-type-assertions: true
  gocritic:
    settings:
      captLocal:
        # Whether to restrict checker to params only.
        paramsOnly: false
      underef:
        # Whether to skip (*x).method() calls where x is a pointer receiver.
        skipRecvDeref: false
  govet:
    # Enable all analyzers.
    enable-all: true
    disable:
      - fieldalignment # reports struct fields that could be re-ordered to save space, disabled because little gain for much pain
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        strict: true
linters:
  disable-all: true
  enable:
    # Enabled by default.
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - unused # checks for unused constants, variables, functions and types
    # Disabled by default.
    - gocritic # provides diagnostics that check for bugs, performance and style issues
    - goimports # in addition to fixing imports, goimports also formats your code in the same style as gofmt
    - gosec # inspects source code for security problems
    - lll # reports long lines
    - revive # fast, configurable, extensible, flexible, and beautiful linter for Go, drop-in replacement of golint
issues:
  max-same-issues: 50
