services:
  database:
    image: postgres:16-alpine
    env_file: example.env
    ports:
      - "${CUSTOM_DATABASE_PORT:-5432}:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 10s
      timeout: 3s
      retries: 3
  database-up:
    build: .
    entrypoint: ["database-up"]
    env_file:
      - example.env
    environment:
      - APP_DATABASE_DSN=postgres://postgres:postgres@database:5432/postgres
    depends_on:
      database:
        condition: service_healthy
  server:
    build: .
    entrypoint: ["server"]
    env_file:
      - example.env
    environment:
      - APP_SERVER_HOST=0.0.0.0
      - APP_SERVER_PORT=8000
      - APP_DATABASE_DSN=postgres://postgres:postgres@database:5432/postgres
      - APP_PEOPLE_INFO_SERVER_URL=http://peopleinfo:8000
    ports:
      - "${CUSTOM_SERVER_PORT:-8000}:8000"
    depends_on:
      database-up:
        condition: service_completed_successfully
  peopleinfo:
    build: .
    entrypoint: ["peopleinfoserver"]
    env_file:
      - example.env
    environment:
      - APP_SERVER_HOST=0.0.0.0
      - APP_SERVER_PORT=8000
    ports:
      - "${CUSTOM_PEOPLE_INFO_SERVER_PORT:-8001}:8000"
volumes:
  database-data:
