openapi: 3.0.3
info:
  title: TimeTrack
  version: 0.0.0
paths: {}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: OAuth2
  responses:
    UnauthorizedError:
      description: Unauthorized